### ISSUE TITLE
Server sometimes closes connection

### ISSUE THREAD

**Issue by sagilo** [sagilo/pyswitcherv2#3]
It usually happens when trying to sign in too many times in a short period.
The login request fails and the socket is closed by server.
The company is aware of the issue and hopefully a fixed will be released soon.
In the meanwhile, a retry mechanism is implemented.

**Comment by nitaybz** [comment]
sometimes when trying to change the status it get stuck and I'm getting this output:
is this the bug or should I open a new issue?
```
Dec 11 06:39:57 raspberrypi homebridge[10291]: [2018-12-11 06:39:57] [CMD Switch] Failed to turn on Boiler
Dec 11 06:39:57 raspberrypi homebridge[10291]: [2018-12-11 06:39:57] [CMD Switch] Traceback (most recent call last):
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 159, in _control
Dec 11 06:39:57 raspberrypi homebridge[10291]:     session = self.__send_local_sign_in()
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 267, in __send_local_sign_in
Dec 11 06:39:57 raspberrypi homebridge[10291]:     session, response = self.__send_request_get_response(request)
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 191, in __send_request_get_response
Dec 11 06:39:57 raspberrypi homebridge[10291]:     return self.__recv_response()
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 181, in __recv_response
Dec 11 06:39:57 raspberrypi homebridge[10291]:     raise ServerClosed("ERROR: failed getting response (server closed)")
Dec 11 06:39:57 raspberrypi homebridge[10291]: __main__.ServerClosed: ERROR: failed getting response (server closed)
Dec 11 06:39:57 raspberrypi homebridge[10291]: During handling of the above exception, another exception occurred:
Dec 11 06:39:57 raspberrypi homebridge[10291]: Traceback (most recent call last):
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 159, in _control
Dec 11 06:39:57 raspberrypi homebridge[10291]:     session = self.__send_local_sign_in()
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 267, in __send_local_sign_in
Dec 11 06:39:57 raspberrypi homebridge[10291]:     session, response = self.__send_request_get_response(request)
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 191, in __send_request_get_response
Dec 11 06:39:57 raspberrypi homebridge[10291]:     return self.__recv_response()
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 181, in __recv_response
Dec 11 06:39:57 raspberrypi homebridge[10291]:     raise ServerClosed("ERROR: failed getting response (server closed)")
Dec 11 06:39:57 raspberrypi homebridge[10291]: __main__.ServerClosed: ERROR: failed getting response (server closed)
Dec 11 06:39:57 raspberrypi homebridge[10291]: During handling of the above exception, another exception occurred:
Dec 11 06:39:57 raspberrypi homebridge[10291]: Traceback (most recent call last):
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 159, in _control
Dec 11 06:39:57 raspberrypi homebridge[10291]:     session = self.__send_local_sign_in()
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 267, in __send_local_sign_in
Dec 11 06:39:57 raspberrypi homebridge[10291]:     session, response = self.__send_request_get_response(request)
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 191, in __send_request_get_response
Dec 11 06:39:57 raspberrypi homebridge[10291]:     return self.__recv_response()
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 181, in __recv_response
Dec 11 06:39:57 raspberrypi homebridge[10291]:     raise ServerClosed("ERROR: failed getting response (server closed)")
Dec 11 06:39:57 raspberrypi homebridge[10291]: __main__.ServerClosed: ERROR: failed getting response (server closed)
Dec 11 06:39:57 raspberrypi homebridge[10291]: During handling of the above exception, another exception occurred:
Dec 11 06:39:57 raspberrypi homebridge[10291]: Traceback (most recent call last):
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 569, in <module>
Dec 11 06:39:57 raspberrypi homebridge[10291]:     main()
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 565, in main
Dec 11 06:39:57 raspberrypi homebridge[10291]:     sys.exit(run(args))
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 551, in run
Dec 11 06:39:57 raspberrypi homebridge[10291]:     return switcher.turn_on(args.time_min)
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 151, in turn_on
Dec 11 06:39:57 raspberrypi homebridge[10291]:     return self._control(True, time_minutes, 1)
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 171, in _control
Dec 11 06:39:57 raspberrypi homebridge[10291]:     self._control(False, 0, retry_num + 1)
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 171, in _control
Dec 11 06:39:57 raspberrypi homebridge[10291]:     self._control(False, 0, retry_num + 1)
Dec 11 06:39:57 raspberrypi homebridge[10291]:   File "/home/homebridge/.local/lib/python3.5/site-packages/pyswitcherv2/switcher.py", line 168, in _control
```
