### ISSUE TITLE
Parsing pcap file issue

### ISSUE THREAD

**Issue by TheBlackBush** [sagilo/pyswitcherv2#4]
When i try to parse from master branch i get the error
```
BuSHari@DiskStation:~/pyswitcherv2/pyswitcherv2$ sudo python switcher.py -m parse_pcap_file -f avraham_switcher.pcap -d
2018-03-14 07:11:57
Retrying in 3 seconds
Retrying in 6 seconds
ERROR: Reached max num of retries (3), exiting...
```

and this is the error when i try it from the dev branch
```
BuSHari@DiskStation:~/pyswitcherv2/pyswitcherv2$ sudo python switcher.py -m parse_pcap_file -f avraham_switcher.pcap -d
2018-03-14 07:35:17 | mode: parse_pcap_file
Traceback (most recent call last):
  File "switcher.py", line 477, in <module>
    main()
  File "switcher.py", line 474, in main
    exit(run(args, 1))
  File "switcher.py", line 443, in run
    parse_pcap_file(args.pcap_file)
  File "switcher.py", line 365, in parse_pcap_file
    device_id, phone_id, device_pass = extract_credentials_from_pcap(file_path)
  File "switcher.py", line 230, in extract_credentials_from_pcap
    from pcapfile import savefile
ImportError: No module named pcapfile
```

**Comment by TheBlackBush** [comment]
I've installed the package pypcapfile

```
BuSHari@DiskStation:~/pyswitcherv2/pyswitcherv2$ pip show pypcapfile
Name: pypcapfile
Version: 0.12.0
Summary: Pure Python package for reading and parsing libpcap savefiles.
Home-page: http://kisom.github.com/pypcapfile
Author: Kyle Isom
Author-email: coder@kyleisom.net
License: ISC
Location: /volume1/@appstore/python/lib/python2.7/site-packages
Requires:
```

**Comment by sagilo** [comment]
The error says it's not found.
Maybe you installed for a different python ver or viertual env?

**Comment by TheBlackBush** [comment]
This is happen only in the dev branch and not the master, in the master i get other error (see above)

**Comment by TheBlackBush** [comment]
when i try to run it through the pip version (and not the cloned repo)
it seems to be ok now:

```
BuSHari@DiskStation:~/pyswitcherv2/pyswitcherv2$ pyswitcherv2 -m parse_pcap_file -f avraham_switcher.pcap -d
2018-03-14 08:47:04
Loading and parsing pcap file:
[+] attempting to load avraham_switcher.pcap
[+] found valid header
[+] loaded 46 packets
[+] finished loading savefile.


Not control command, continuing to next packet, command: 4354
Not control command, continuing to next packet, command: 4354
Not control command, continuing to next packet, command: 4867
Not control command, continuing to next packet, command: 4610
Not control command, continuing to next packet, command: 4867
Not control command, continuing to next packet, command: 4610
Not control command, continuing to next packet, command: 769
Not control command, continuing to next packet, command: 769
Not control command, continuing to next packet, command: 769
Not control command, continuing to next packet, command: 769
Device ID (did): xxxxxx
Phone ID (uid): xxxx
Device pass: xxxxxx
Wrote credential files successfully. Please update Switcher IP address (credentials.json)
```

**Comment by sagilo** [comment]
This is something with your `pip` and `python`.
You installed `pypcapfile` using `pip` and the default python finds it, however, when you use `python` it doesn't.
Can you please run `which pip` and `which python` and make sure they both belong to the same version and environment.

**Comment by TheBlackBush** [comment]
```
BuSHari@DiskStation:/var/packages/python/target$ which pip
/var/packages/python/target/bin/pip
BuSHari@DiskStation:/var/packages/python/target$ which python
/bin/python
```

**Comment by sagilo** [comment]
That's exactly the issue.
You install the package for the `pip` in `/var/packages/python/target/bin`
Try running `/var/packages/python/target/bin/python swithcer.py -m parse_pcap_file -f xxx` and it will probably work.
Or you can install the `pyparsefile` package to the relevant pip in `/bin/pip install pypcapfile`
Either way it's an issue with your python/pip paths and not with the library.

**Comment by TheBlackBush** [comment]
ok, it's working now.
I've installed the pip in /bin folder
