### ISSUE TITLE
Fix print time - issue in Docker

### ISSUE THREAD

**Issue by TheBlackBush** [sagilo/pyswitcherv2#9]
When trying to run the script under a docker container i get an error
```
root@Home-Assistant:/config/custom_components/switcher# python /config/custom_components/switcher/switcher.py -m get_state
%s
Traceback (most recent call last):
  File "/config/custom_components/switcher/switcher.py", line 387, in <module>
    main()
  File "/config/custom_components/switcher/switcher.py", line 383, in main
    print("%s") % time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime())
TypeError: unsupported operand type(s) for %: 'NoneType' and 'str'
```

you need to fix the code in the end, to this:
```
def main():
    args = parse_args()
    print(time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime()))
    exit(run(args, 1))
```

also, please be aware of the space and tabs in the code

**Comment by sagilo** [comment]
Thanks
Fixed 094db67ae3f75bf5eef8c3ba5e6047e27f6ffe15
